version: '3'

services:
###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
    
    webserver:
        image: 'nginx:alpine'
        working_dir: /api-platform3-task
        volumes:
            - '.:/api-platform3-task'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /api-platform3-task
        volumes:
            - '.:/api-platform3-task'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

###< doctrine/doctrine-bundle ###
volumes:
###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###